language: python

python:
  - "3.6"

install:
  - pip install -r requirements.txt
  - pip install codecov

script: 

  - pytest
  - coverage run python/test_valid_parentheses.py

after_success:
  - codecov
  - coveralls
